// Copyright 2026 Brightfellow contributors
// SPDX-License-Identifier: Apache-2.0

// Package domain holds entities and rules. It imports only the standard library.
package domain

// IDs are ULIDs (26 characters), generated by the application, never the database.
type (
	// ChurchID identifies a church.
	ChurchID string
	// UserID identifies a user.
	UserID string
	// MembershipID identifies a user's membership in a church.
	MembershipID string
	// RoleID identifies a church's role.
	RoleID string
	// InviteID identifies an invite.
	InviteID string
	// TranslationID identifies a Bible translation.
	TranslationID string
	// SongID identifies a song of a church (06).
	SongID string
	// SectionID identifies one section (verse, chorus …) of a song.
	SectionID string
	// SongGroupID identifies the group that links the language versions of a hymn.
	SongGroupID string
	// ReadingID identifies a stored reading of a church (07).
	ReadingID string
)
