// Copyright 2026 Brightfellow contributors
// SPDX-License-Identifier: Apache-2.0

// Package domain holds entities and rules. It imports only the standard library.
package domain

// IDs are ULIDs (26 characters), generated by the application, never the database.
type (
	// ChurchID identifies a church.
	ChurchID string
	// UserID identifies a user.
	UserID string
)
