/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password with a reset link */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Describe a reset link */
        post: operations["inspectReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/church": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The church */
        get: operations["getChurch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change church settings */
        patch: operations["updateChurch"];
        trace?: never;
    };
    "/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending and expired invites */
        get: operations["listInvites"];
        put?: never;
        /** Invite a person */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an invite as a new user */
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/accept-existing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an invite with the logged-in account */
        post: operations["acceptInviteExisting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Describe an invite link */
        post: operations["inspectInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel an invite */
        delete: operations["cancelInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New link for an invite */
        post: operations["regenerateInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The logged-in user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change name or preferences */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change own password */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/sessions/end-others": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out on all other devices */
        post: operations["endOtherSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Members of the church */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{membershipId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        /** Assign roles to a member */
        patch: operations["setMemberRoles"];
        trace?: never;
    };
    "/members/{membershipId}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a password-reset link for a member */
        post: operations["createResetLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search and list readings */
        get: operations["listReadings"];
        put?: never;
        /** Save a reading typed or pasted by a member */
        post: operations["createReading"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readings/from-provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save the text a registered provider returns */
        post: operations["createReadingFromProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readings/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find the text for a reference */
        get: operations["lookupReading"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readings/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Understand a typed Bible reference */
        get: operations["parseReference"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A reading with its text */
        get: operations["getReading"];
        put?: never;
        post?: never;
        /** Delete a reading */
        delete: operations["deleteReading"];
        options?: never;
        head?: never;
        /** Change the text or attribution of a reading */
        patch: operations["updateReading"];
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roles of the church */
        get: operations["listRoles"];
        put?: never;
        /** Create a role */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a role */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        /** Rename a role or change its scopes */
        patch: operations["updateRole"];
        trace?: never;
    };
    "/scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scopes with descriptions */
        get: operations["listScopes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the church and its first admin */
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the church has been set up */
        get: operations["getSetupStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search and list songs */
        get: operations["listSongs"];
        put?: never;
        /** Add a song */
        post: operations["createSong"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A song with its sections */
        get: operations["getSong"];
        put?: never;
        post?: never;
        /** Delete a song */
        delete: operations["deleteSong"];
        options?: never;
        head?: never;
        /** Change a song, its sections or its arrangement */
        patch: operations["updateSong"];
        trace?: never;
    };
    "/songs/{id}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link another-language version of the same hymn */
        post: operations["linkSong"];
        /** Unlink a song from its other-language versions */
        delete: operations["unlinkSong"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bible translations */
        get: operations["listTranslations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptInviteRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/AcceptInviteRequest.json
             */
            readonly $schema?: string;
            email?: string;
            name: string;
            password: string;
            phone?: string;
            token: string;
        };
        AdminStruct: {
            identifier: string;
            name: string;
            password: string;
        };
        ChangePasswordRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ChangePasswordRequest.json
             */
            readonly $schema?: string;
            current_password: string;
            new_password: string;
        };
        ChurchActions: {
            edit: boolean;
        };
        ChurchStruct: {
            default_language: string;
            default_translation_code: string;
            default_ui_language: string;
            key_display: string;
            name: string;
            time_zone: string;
        };
        ChurchView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ChurchView.json
             */
            readonly $schema?: string;
            actions: components["schemas"]["ChurchActions"];
            /** @enum {string} */
            default_language: "id" | "en" | "zh-Hans" | "zh-Hant";
            default_translation_code: string;
            /** @enum {string} */
            default_ui_language: "en" | "id";
            feedback_url: string | null;
            id: string;
            /** @enum {string} */
            key_display: "do" | "letter";
            name: string;
            privacy_contact: string | null;
            time_zone: string;
        };
        CreateInviteRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/CreateInviteRequest.json
             */
            readonly $schema?: string;
            email?: string;
            name: string;
            phone?: string;
            role_ids?: string[] | null;
        };
        CreateReadingFromProviderRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/CreateReadingFromProviderRequest.json
             */
            readonly $schema?: string;
            provider: string;
            reference: string;
            translation?: string;
        };
        CreateReadingRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/CreateReadingRequest.json
             */
            readonly $schema?: string;
            attribution?: string;
            reference: string;
            text: string;
            /** @description default: the church's translation */
            translation?: string;
        };
        CreateRoleRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/CreateRoleRequest.json
             */
            readonly $schema?: string;
            description?: string;
            name: string;
            scopes: string[] | null;
        };
        CreateSongRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/CreateSongRequest.json
             */
            readonly $schema?: string;
            alt_titles?: string[] | null;
            ccli_song_number?: string;
            composer?: string;
            copyright_holder?: string;
            copyright_line?: string;
            /** @description keys of the new sections */
            default_arrangement?: string[] | null;
            default_key?: string;
            hymnal_number?: string;
            hymnal_source?: string;
            /** @enum {string} */
            language: "id" | "en" | "zh-Hans" | "zh-Hant";
            licence_notes?: string;
            /** @enum {string} */
            licence_status?: "unknown" | "public_domain" | "church_licence" | "permission_obtained";
            lyricist?: string;
            sections?: components["schemas"]["SongSection"][] | null;
            title: string;
            translator?: string;
        };
        CreatedInviteOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/CreatedInviteOutputBody.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            expires_at: string;
            invite: components["schemas"]["InviteView"];
            /** @description Shown only now and after regenerating */
            link: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        InviteActions: {
            cancel: boolean;
            regenerate: boolean;
        };
        InviteInfoOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/InviteInfoOutputBody.json
             */
            readonly $schema?: string;
            church_name: string;
            email: string | null;
            invitee_name: string;
            /** @description The invite's email or phone belongs to an existing account */
            owner_exists: boolean;
            phone: string | null;
            /** @enum {string} */
            status: "pending";
        };
        InviteView: {
            actions: components["schemas"]["InviteActions"];
            /** Format: date-time */
            created_at: string;
            created_by_name: string | null;
            email: string | null;
            /** Format: date-time */
            expires_at: string;
            id: string;
            name: string;
            phone: string | null;
            roles: components["schemas"]["RoleRef"][] | null;
            /** @enum {string} */
            status: "pending" | "expired";
        };
        Item: {
            code: string;
            language: string;
            name: string;
        };
        Item1: {
            description: string;
            scope: string;
        };
        LinkSongRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/LinkSongRequest.json
             */
            readonly $schema?: string;
            other_song_id: string;
        };
        LinkView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/LinkView.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            expires_at: string;
            link: string;
        };
        LoginRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/LoginRequest.json
             */
            readonly $schema?: string;
            /** @description Email or phone number */
            identifier: string;
            password: string;
        };
        LookupView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/LookupView.json
             */
            readonly $schema?: string;
            canonical: string;
            display: string;
            /** @description text a registered provider offers, if no reading is saved */
            provider: components["schemas"]["ProviderTextView"];
            /** @description a provider could not be reached and nothing was found */
            provider_error: boolean;
            /** @description the church's saved reading, if any */
            reading: components["schemas"]["ReadingView"];
            reference: string;
            suggested_attribution: string;
            translation: components["schemas"]["TranslationRefView"];
        };
        MeOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/MeOutputBody.json
             */
            readonly $schema?: string;
            /** @description null before setup or when not a member of the church */
            church: components["schemas"]["ChurchView"];
            /** @description null before setup or when not a member of the church */
            membership: components["schemas"]["MembershipView"];
            user: components["schemas"]["UserView"];
        };
        MemberActions: {
            create_reset_link: boolean;
            edit_roles: boolean;
            remove: boolean;
        };
        MemberView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/MemberView.json
             */
            readonly $schema?: string;
            actions: components["schemas"]["MemberActions"];
            email: string | null;
            id: string;
            /** Format: date-time */
            joined_at: string;
            /** @description Only for viewers with members.manage */
            last_reset?: components["schemas"]["ResetView"];
            name: string;
            phone: string | null;
            roles: components["schemas"]["RoleRef"][] | null;
            user_id: string;
        };
        MembersOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/MembersOutputBody.json
             */
            readonly $schema?: string;
            members: components["schemas"]["MemberView"][] | null;
            usage: components["schemas"]["UsageStruct"];
        };
        MembershipView: {
            actions: components["schemas"]["MemberActions"];
            id: string;
            roles: components["schemas"]["RoleRef"][] | null;
            scopes: string[] | null;
        };
        ParsedReferenceView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ParsedReferenceView.json
             */
            readonly $schema?: string;
            /** @description with the Indonesian book name */
            canonical: string;
            /** @description as typed, spaces collapsed */
            display: string;
            /** @description standard form */
            reference: string;
        };
        Preferences: {
            text_size?: string;
            ui_language?: string;
        };
        PreferencesStruct: {
            text_size?: string;
            ui_language?: string | null;
        };
        Problem: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/Problem.json
             */
            readonly $schema?: string;
            code: string;
            detail?: string;
            errors?: components["schemas"]["ErrorDetail"][] | null;
            limit?: string;
            /** Format: int64 */
            max?: number;
            reading_id?: string;
            reason?: string;
            scopes?: string[] | null;
            section_ids?: string[] | null;
            /** Format: int64 */
            status: number;
            title: string;
            /** Format: int64 */
            used?: number;
        };
        ProviderTextView: {
            attribution: string;
            may_store: boolean;
            /** @description the provider's ID, for POST /readings/from-provider */
            source: string;
            text: string;
        };
        ReadingActions: {
            delete: boolean;
            edit: boolean;
        };
        ReadingListOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ReadingListOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["ReadingSummaryView"][] | null;
            /** Format: int64 */
            total: number;
        };
        ReadingSummaryView: {
            actions: components["schemas"]["ReadingActions"];
            /** @description with the Indonesian book name, e.g. Yohanes 3:16-21 */
            canonical: string;
            id: string;
            /** @description standard form, e.g. JHN 3:16-21 */
            reference: string;
            /** @description as typed */
            reference_display: string;
            snippet: string;
            translation: components["schemas"]["TranslationRefView"];
        };
        ReadingView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ReadingView.json
             */
            readonly $schema?: string;
            actions: components["schemas"]["ReadingActions"];
            attribution: string;
            canonical: string;
            /** Format: date-time */
            created_at: string;
            id: string;
            reference: string;
            reference_display: string;
            /** @description manual, or the ID of the provider the text came from */
            source_provider: string;
            text: string;
            translation: components["schemas"]["TranslationRefView"];
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: int64
             * @description send it back with every change
             */
            version: number;
        };
        ResetInfoOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ResetInfoOutputBody.json
             */
            readonly $schema?: string;
            /** @description null: created by the server administrator */
            created_by_name: string | null;
            /** Format: date-time */
            expires_at: string;
            user_name: string;
        };
        ResetPasswordRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/ResetPasswordRequest.json
             */
            readonly $schema?: string;
            new_password: string;
            token: string;
        };
        ResetView: {
            /** Format: date-time */
            created_at: string;
            /** @description null: created on the server's command line */
            created_by_name: string | null;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            used_at: string | null;
        };
        RoleActions: {
            delete: boolean;
            edit: boolean;
        };
        RoleRef: {
            id: string;
            name: string;
        };
        RoleView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/RoleView.json
             */
            readonly $schema?: string;
            actions: components["schemas"]["RoleActions"];
            description: string;
            id: string;
            /** Format: int64 */
            member_count: number;
            name: string;
            /** @description Ready-made role this started as; null for custom roles */
            origin: string | null;
            scopes: string[] | null;
        };
        SectionView: {
            id: string;
            /** @enum {string} */
            kind: "verse" | "pre_chorus" | "chorus" | "bridge" | "tag" | "intro" | "ending" | "other";
            /** @description null: derive from kind and number */
            label: string | null;
            /**
             * Format: int64
             * @description verses only
             */
            number: number | null;
            text: string;
        };
        SetMemberRolesRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/SetMemberRolesRequest.json
             */
            readonly $schema?: string;
            role_ids: string[] | null;
        };
        SetupRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/SetupRequest.json
             */
            readonly $schema?: string;
            admin: components["schemas"]["AdminStruct"];
            church: components["schemas"]["ChurchStruct"];
            token: string;
        };
        SongActions: {
            delete: boolean;
            edit: boolean;
        };
        SongListOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/SongListOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["SongSummaryView"][] | null;
            /** Format: int64 */
            total: number;
        };
        SongRefView: {
            id: string;
            /** @enum {string} */
            language: "id" | "en" | "zh-Hans" | "zh-Hant";
            title: string;
        };
        SongSection: {
            /** @description an existing section of this song; omit for a new one */
            id?: string;
            /** @description request-local name of a new section, for default_arrangement */
            key?: string;
            /** @enum {string} */
            kind: "verse" | "pre_chorus" | "chorus" | "bridge" | "tag" | "intro" | "ending" | "other";
            label?: string;
            /**
             * Format: int64
             * @description verses only (1-99)
             */
            number?: number;
            text: string;
        };
        SongSummaryView: {
            actions: components["schemas"]["SongActions"];
            alt_titles: string[] | null;
            has_group: boolean;
            hymnal_number: string;
            hymnal_source: string;
            id: string;
            /** @enum {string} */
            language: "id" | "en" | "zh-Hans" | "zh-Hant";
            /** @enum {string} */
            licence_status: "unknown" | "public_domain" | "church_licence" | "permission_obtained";
            title: string;
        };
        SongView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/SongView.json
             */
            readonly $schema?: string;
            actions: components["schemas"]["SongActions"];
            alt_titles: string[] | null;
            ccli_song_number: string;
            composer: string;
            copyright_holder: string;
            copyright_line: string;
            /** Format: date-time */
            created_at: string;
            /** @description section IDs; empty: none defined, use all sections in order */
            default_arrangement: string[] | null;
            default_key: string;
            hymnal_number: string;
            hymnal_source: string;
            id: string;
            /** @enum {string} */
            language: "id" | "en" | "zh-Hans" | "zh-Hant";
            licence_notes: string;
            /** @enum {string} */
            licence_status: "unknown" | "public_domain" | "church_licence" | "permission_obtained";
            lyricist: string;
            sections: components["schemas"]["SectionView"][] | null;
            title: string;
            translator: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: int64
             * @description send it back with every change
             */
            version: number;
            /** @description the other-language versions linked to this song */
            versions: components["schemas"]["SongRefView"][] | null;
        };
        StatusOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/StatusOutputBody.json
             */
            readonly $schema?: string;
            set_up: boolean;
        };
        TeamMembersStruct: {
            /**
             * Format: int64
             * @description null when unlimited
             */
            max: number | null;
            /** Format: int64 */
            used: number;
        };
        TokenBodyBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/TokenBodyBody.json
             */
            readonly $schema?: string;
            token: string;
        };
        TranslationRefView: {
            code: string;
            /** @enum {string} */
            language: "id" | "en" | "zh-Hans" | "zh-Hant";
            name: string;
        };
        UpdateChurchRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/UpdateChurchRequest.json
             */
            readonly $schema?: string;
            default_language?: string;
            default_translation_code?: string;
            default_ui_language?: string;
            /** @description null or "" clears */
            feedback_url?: string | null;
            key_display?: string;
            name?: string;
            /** @description null or "" clears */
            privacy_contact?: string | null;
            time_zone?: string;
        };
        UpdateMeRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/UpdateMeRequest.json
             */
            readonly $schema?: string;
            name?: string;
            preferences?: components["schemas"]["PreferencesStruct"];
        };
        UpdateReadingRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/UpdateReadingRequest.json
             */
            readonly $schema?: string;
            attribution?: string;
            reference_display?: string;
            text?: string;
            /**
             * Format: int64
             * @description the version the client loaded
             */
            version: number;
        };
        UpdateRoleRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/UpdateRoleRequest.json
             */
            readonly $schema?: string;
            description?: string;
            name?: string;
            scopes?: string[];
        };
        UpdateSongRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/UpdateSongRequest.json
             */
            readonly $schema?: string;
            alt_titles?: string[];
            ccli_song_number?: string;
            composer?: string;
            copyright_holder?: string;
            copyright_line?: string;
            /** @description section IDs or keys of new sections; [] clears it */
            default_arrangement?: string[];
            default_key?: string;
            hymnal_number?: string;
            hymnal_source?: string;
            /** @enum {string} */
            language?: "id" | "en" | "zh-Hans" | "zh-Hant";
            licence_notes?: string;
            /** @enum {string} */
            licence_status?: "unknown" | "public_domain" | "church_licence" | "permission_obtained";
            lyricist?: string;
            /** @description the complete ordered list; omitted sections are deleted */
            sections?: components["schemas"]["SongSection"][];
            title?: string;
            translator?: string;
            /**
             * Format: int64
             * @description the version the client loaded
             */
            version: number;
        };
        UsageStruct: {
            team_members: components["schemas"]["TeamMembersStruct"];
        };
        UserView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/schemas/UserView.json
             */
            readonly $schema?: string;
            email: string | null;
            id: string;
            name: string;
            phone: string | null;
            preferences: components["schemas"]["Preferences"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    inspectReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenBodyBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetInfoOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getChurch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChurchView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateChurch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChurchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChurchView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listInvites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteView"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedInviteOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    acceptInviteExisting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenBodyBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    inspectInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenBodyBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteInfoOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    cancelInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    regenerateInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    endOtherSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembersOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membershipId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    setMemberRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membershipId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMemberRolesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createResetLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membershipId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listReadings: {
        parameters: {
            query?: {
                /** @description part of the reference or the text */
                q?: string;
                translation?: string;
                /** @description default 50, at most 100 */
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createReading: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReadingRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createReadingFromProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReadingFromProviderRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    lookupReading: {
        parameters: {
            query?: {
                reference?: string;
                /** @description default: the church's translation */
                translation?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookupView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    parseReference: {
        parameters: {
            query?: {
                input?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedReferenceView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getReading: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteReading: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateReading: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReadingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleView"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listScopes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item1"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listSongs: {
        parameters: {
            query?: {
                /** @description title, hymnal number or lyrics */
                q?: string;
                language?: string;
                licence_status?: string;
                hymnal_source?: string;
                /** @description exact; needs hymnal_source */
                hymnal_number?: string;
                /** @description default 50, at most 100 */
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createSong: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSongRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getSong: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteSong: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateSong: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSongRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    linkSong: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkSongRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    unlinkSong: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listTranslations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
